// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: FoodCompanyGateWayService.proto

package FoodCompanyGateWay

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoodCompanyGateWayService_GetOrderStatus_FullMethodName = "/FoodCompanyGateWayService/GetOrderStatus"
)

// FoodCompanyGateWayServiceClient is the client API for FoodCompanyGateWayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodCompanyGateWayServiceClient interface {
	GetOrderStatus(ctx context.Context, in *GetOrderStatusRequest, opts ...grpc.CallOption) (*GetOrderStatusResponse, error)
}

type foodCompanyGateWayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodCompanyGateWayServiceClient(cc grpc.ClientConnInterface) FoodCompanyGateWayServiceClient {
	return &foodCompanyGateWayServiceClient{cc}
}

func (c *foodCompanyGateWayServiceClient) GetOrderStatus(ctx context.Context, in *GetOrderStatusRequest, opts ...grpc.CallOption) (*GetOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderStatusResponse)
	err := c.cc.Invoke(ctx, FoodCompanyGateWayService_GetOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodCompanyGateWayServiceServer is the server API for FoodCompanyGateWayService service.
// All implementations must embed UnimplementedFoodCompanyGateWayServiceServer
// for forward compatibility.
type FoodCompanyGateWayServiceServer interface {
	GetOrderStatus(context.Context, *GetOrderStatusRequest) (*GetOrderStatusResponse, error)
	mustEmbedUnimplementedFoodCompanyGateWayServiceServer()
}

// UnimplementedFoodCompanyGateWayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodCompanyGateWayServiceServer struct{}

func (UnimplementedFoodCompanyGateWayServiceServer) GetOrderStatus(context.Context, *GetOrderStatusRequest) (*GetOrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderStatus not implemented")
}
func (UnimplementedFoodCompanyGateWayServiceServer) mustEmbedUnimplementedFoodCompanyGateWayServiceServer() {
}
func (UnimplementedFoodCompanyGateWayServiceServer) testEmbeddedByValue() {}

// UnsafeFoodCompanyGateWayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodCompanyGateWayServiceServer will
// result in compilation errors.
type UnsafeFoodCompanyGateWayServiceServer interface {
	mustEmbedUnimplementedFoodCompanyGateWayServiceServer()
}

func RegisterFoodCompanyGateWayServiceServer(s grpc.ServiceRegistrar, srv FoodCompanyGateWayServiceServer) {
	// If the following call pancis, it indicates UnimplementedFoodCompanyGateWayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoodCompanyGateWayService_ServiceDesc, srv)
}

func _FoodCompanyGateWayService_GetOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodCompanyGateWayServiceServer).GetOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodCompanyGateWayService_GetOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodCompanyGateWayServiceServer).GetOrderStatus(ctx, req.(*GetOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodCompanyGateWayService_ServiceDesc is the grpc.ServiceDesc for FoodCompanyGateWayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodCompanyGateWayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FoodCompanyGateWayService",
	HandlerType: (*FoodCompanyGateWayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderStatus",
			Handler:    _FoodCompanyGateWayService_GetOrderStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "FoodCompanyGateWayService.proto",
}
